### ISSUE TITLE
Japanese ordinal numbers

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#101]
問題：
人名につくローマ数字を「〜世」に置き換えたい。

再現性：
常に

再現手順：
省略

解決策：
不明

参考画像：

試験中の日本語人名バージョン
![japan4](https://user-images.githubusercontent.com/42687608/50391692-3a365a80-078b-11e9-83e6-8a9148a80110.jpg)

**Comment by oooFUNooo** [comment]
日本・中国・朝鮮など序数が要らない場合は、
common/countries のファイルから #0 を削除すれば良いことがわかった。

その他の国に関しては、翻訳をローマ数字に統一することで対処する。

**Comment by oooFUNooo** [comment]
2019年2月9日午後5時より、序数を一斉にローマ数字に置換します。
同時に、次のページに掲載されている国の君主名候補から序数を削除します。
[EU4 Wiki Asia eastern regions](https://eu4.paradoxwikis.com/Asia_eastern_regions)

**Comment by oooFUNooo** [comment]
ParaTranzで一カ国ずつ強制上書きしないとダメなことが判明したため、修正を保留しました。

**Comment by matanki-saito** [comment]
historiesは連続インポートできましたが、commonのファイルについてできないようです。

**Comment by matanki-saito** [comment]
paratranz側のシステムで対応していないため、難しそうです

**Comment by matanki-saito** [comment]
要望が出されていますのでいったんCloseします
