### ISSUE TITLE
Text garbling on the paticular character

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#102]
問題：
特定の文字が桁あふれで省略されると文字化けする。

再現性：
常に

再現手順：
1. 1700年前後まで進めたセーブデータを用意する。
2. 台帳の「継続中の戦争」を開く。
3. 「帝国主義」または「民族主義」の「主」が省略されると「※」という文字に化ける。

原因：
文字列の省略まわりの問題だと推測される。

解決策：
不明

参考画像：
![ss](https://user-images.githubusercontent.com/42687608/50533940-ef945400-0b77-11e9-9452-377fe51317e4.png)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс
