### ISSUE TITLE
checksum issue when playing multiplayer

### ISSUE THREAD

**Issue by qiz029** [matanki-saito/EU4dll#112]
I used this plugin in my EU4 with my friend who used the same version of EU4dll. but we are having a issue with our unmatched checksum

the multiplayer works fine for us when it comes with vanilla game.

Thanks

**Comment by matanki-saito** [comment]
Please check if your team is using the same Mod.

**Comment by matanki-saito** [comment]
hmm, I will examine the checksum logic.

**Comment by TaihouKai** [comment]
> Your checksum d9f4 has no problem, I think.
> 
> I supporse your environments are following;
> 
> * use EU4 version 1.28.2.0
> * use appropriate EU4dll
> * use no Mods or only Ironman compatible Mods
> 
> However your friend's checksum aef6 is unknown.
> Please ask your friend to confirm he/she uses the same environments as you.
> 
> thx.

Hello, I am using the same game version & mod as my friend's. I have tried to reinstall the whole game and it did not work.

Do other system environments affect this issue (e.g. .NET) ?

**Comment by TaihouKai** [comment]
> hmm, I have no idea..
> 
> The list of checksums is following. "aef6" is not on the list.
> 
> * https://eu4.paradoxwikis.com/Patches
> 
> I found a similar case. It may improve. Please confirm.
> 
> * https://steamcommunity.com/app/236850/discussions/0/135512625247777405/
> 
> thx

I will try. Thank you very much for your advice!

**Comment by TaihouKai** [comment]
> hmm, I have no idea..
> 
> The list of checksums is following. "aef6" is not on the list.
> 
> * https://eu4.paradoxwikis.com/Patches
> 
> I found a similar case. It may improve. Please confirm.
> 
> * https://steamcommunity.com/app/236850/discussions/0/135512625247777405/
> 
> thx

Hello, I tried the method mentioned in the link and it worked. Thank you very much.
