### ISSUE TITLE
Extra space in text box

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#134]
問題：
イベントダイアログやスタートアップ画面で、文章のあとに余分な空白ができる。

再現性：
常に

再現手順：
1. 1444年の適当な大国（ポルトガル、ポーランド、ハンガリーなど）で開始し、歴史イベントを発生させる。
2. 英語環境と日本語環境のイベントダイアログを比較する。

原因：
不明
おそらくエスケープシーケンス絡みで文字幅の計算に失敗しているものと推測される。
症状は [Issue #46](https://github.com/matanki-saito/EU4dll/issues/46) と類似している。

解決策：
不明

参考画像：

英語環境（正常）
![dialog_normal](https://user-images.githubusercontent.com/42687608/54083392-f0124d80-4365-11e9-88de-7f906fcb10a0.jpg)

日本語環境（異常）
![dialog_issue](https://user-images.githubusercontent.com/42687608/54083397-015b5a00-4366-11e9-8812-84642b3850ba.jpg)

**Comment by matanki-saito** [comment]
この部分とも関係があるかもしれません
![image](https://user-images.githubusercontent.com/35730970/54083498-6fece780-4367-11e9-8e93-24c11df4609e.png)

**Comment by matanki-saito** [comment]
この余白はおそらく処理そのものよりもline-heightと関係があります。

**Comment by matanki-saito** [comment]
```
 string_start_provence:0 "a\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\n"
```
のようにすると、想定通りになる。
![image](https://user-images.githubusercontent.com/35730970/67160936-9e688180-f390-11e9-9787-b1bc5f5ea679.png)

**Comment by matanki-saito** [comment]
マルチバイト、も特に問題ない
![image](https://user-images.githubusercontent.com/35730970/67161007-76c5e900-f391-11e9-88fb-0cc35bdcd821.png)

**Comment by matanki-saito** [comment]
こういう時は
![image](https://user-images.githubusercontent.com/35730970/67161897-e4761300-f399-11e9-80fa-e66491e60212.png)
下の方に自動改行送りになったものが加算される。
![image](https://user-images.githubusercontent.com/35730970/67161966-a75e5080-f39a-11e9-8368-14c49551c70f.png)

**Comment by oooFUNooo** [comment]
つまり、これはline-heightの問題ではなく、ワードラップの問題なのですね。

**Comment by matanki-saito** [comment]
超える部分が、だと問題ない？
![image](https://user-images.githubusercontent.com/35730970/67618174-c475a200-f826-11e9-96e7-1f0a67e266a1.png)

**Comment by matanki-saito** [comment]
年、
```
char id=24180 x=300   y=360   width=15    height=15    xoffset=-1    yoffset=1     xadvance=12    page=0 
```
、
```
char id=12289 x=1274  y=710   width=6     height=6     xoffset=-1    yoffset=10    xadvance=12    page=0 

```

**Comment by matanki-saito** [comment]
両方とも同じように見える...

**Comment by matanki-saito** [comment]
最初に少し加工すると空白は正常になる
![image](https://user-images.githubusercontent.com/35730970/67618511-757e3b80-f82b-11e9-9964-dc4a479cfba1.png)

**Comment by matanki-saito** [comment]
これは、空白が1つ余計にできる
![image](https://user-images.githubusercontent.com/35730970/67618923-68178000-f830-11e9-840f-784b002272c0.png)
また行送りされるものが各行で異なる

**Comment by matanki-saito** [comment]
```
t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0
```
はOK。位置文字足すと余白ができる

**Comment by matanki-saito** [comment]
リミットがあるのはbyte数なのか文字数なのか、幅の総計なのか…

**Comment by matanki-saito** [comment]
これは大丈夫。位置文字増えるとout
```
"t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0t^0aaaaaaaaaaaaaaaaaaaa\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na"
```

**Comment by matanki-saito** [comment]
幅の総計でもない気がする
![image](https://user-images.githubusercontent.com/35730970/67620556-23e1ab00-f843-11e9-831a-4f0f0c802784.png)

**Comment by matanki-saito** [comment]
わからん

**Comment by matanki-saito** [comment]
年のフォントの幅をいじったりもしたが問題ないので、character数の問題か
![image](https://user-images.githubusercontent.com/35730970/67630355-bb89dc80-f8c9-11e9-826d-a2963e4a6546.png)

**Comment by matanki-saito** [comment]
む、文字数を増やしても送り幅が30のときは問題が発生しないがそこから15に戻すと問題が発生するな...

**Comment by matanki-saito** [comment]
わからん彡(ﾟ)(ﾟ)

**Comment by matanki-saito** [comment]
もともとこの改行システムは、長すぎる英文を強制的に改行するための処理をマルチバイト文字列の場合は毎回その処理を実行することで実現している。もともとの処理では2行になるためこの部分の改行がでているのかもしれない。
![image](https://user-images.githubusercontent.com/35730970/67633888-e9d2e080-f8f8-11e9-92ca-1185a934e6a7.png)

**Comment by matanki-saito** [comment]
できた！

<img width="714" alt="image" src="https://user-images.githubusercontent.com/35730970/233814485-a5bae211-47d1-498a-977c-fe5e2157f2c1.png">

**Comment by matanki-saito** [comment]
表題の方はウィンドウが画像なので調整は難しいと思います。
