### ISSUE TITLE
LATEST RELEASE CAUSES CRASH

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/EU4dll#137]
Just these in error.log, I can't find logs for the plugin, I think it was in the game folder before. Running with latest Chinese Language Mod.
```
[main.cpp:412]: 
Game Version: EU4 v1.28.3.0 Spain.5f34a32
Time:2019-04-09 21:15
Configuration: Release
```

**Comment by matanki-saito** [comment]
hmm
 - Did it occur before the start of the game? Were you able to open the launcher? 
 - Did it occur during the game?  Do you remember the CTD trigger?

**Comment by bruceCzK** [comment]
I redownload the patch today. But the issue can not be reproduced. So I guess it has somehow been fixed.
