### ISSUE TITLE
Some chars cannot be used in custom nation name & adj.

### ISSUE THREAD

**Issue by ShekPS** [matanki-saito/EU4dll#138]
For example:

突【尼】斯 (Tunis)
![QQ截图20190413165701](https://user-images.githubusercontent.com/26006407/56077433-c6d65880-5e0e-11e9-9a00-2a467e07513c.png)

迦【太】基 (Carthage)
![QQ截图20190413165726](https://user-images.githubusercontent.com/26006407/56077442-e7061780-5e0e-11e9-8ff5-d3a7230233af.png)

【阿】伊努 (Ainu)
![QQ截图20190413165943](https://user-images.githubusercontent.com/26006407/56077452-f8e7ba80-5e0e-11e9-849c-ff47c76187cc.png)

【尾】张
![QQ截图20190413170628](https://user-images.githubusercontent.com/26006407/56077463-16b51f80-5e0f-11e9-98cd-d0295665b6be.png)

【格】鲁吉亚 (Georgia)
![QQ截图20190413170448](https://user-images.githubusercontent.com/26006407/56077487-6693e680-5e0f-11e9-9e1a-9a03dcb72503.png)

... and many other.

**Comment by ShekPS** [comment]
I thought it is similar to this issue
https://github.com/matanki-saito/EU4SpecialEscape/issues/9

The custom nation name input box don't accept these chars:
@*{}\|<>/?:"
and the incorrect chars seems contains one of them after special escape.

But I tried to modify the functions in FileSave.cpp and Input.cpp but didn't work.

**Comment by matanki-saito** [comment]
Thank you for your report.
This issue is  triggered by "?" character in text sequence.And it is only occurred in custom nation's dialog.

https://github.com/matanki-saito/EU4dll/issues/75

I will add "?" to escape characters.

**Comment by matanki-saito** [comment]
尾 is not good... (ヽ'ω`)

**Comment by ShekPS** [comment]
> 
> 
> I thought it is similar to this issue
> [matanki-saito/EU4SpecialEscape#9](https://github.com/matanki-saito/EU4SpecialEscape/issues/9)
> 
> The custom nation name input box don't accept these chars:
> @*{}|<>/?:"
> and the incorrect chars seems contains one of them after special escape.
> 
> But I tried to modify the functions in FileSave.cpp and Input.cpp but didn't work.

I found actually it's working, but need to re-input the name. 
When you select a province, the custom nation name is from localisation, so need to make the same change in eu4specialescape...

**Comment by ShekPS** [comment]
> 
> 
> 尾 is not good... (ヽ'ω`)

尾 contains '>', it's 0x3E

This is my change
![QQ截图20190420003912](https://user-images.githubusercontent.com/26006407/56433814-d8cf6400-6304-11e9-90d9-5eb7e558da06.png)

**Comment by matanki-saito** [comment]
I have solved this issue. Thank you very much !
