### ISSUE TITLE
CTD on displaying tooltips

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#155]
問題：
特定のツールチップが表示されるタイミングでCTDが発生する。

再現性：
常に

再現手順：
1. ヴェネツィアまたはイングランドで開始する。
2. 国家の決断「制海権を確保」の「？」アイコンにカーソルを合わせる。

原因：
不明
1.28で正常に表示されたツールチップを見ると極めて縦に長い。
このことからツールチップの縦幅、または文字数が原因である可能性が高い。

解決策：
不明

参考画像：

1.28で正常に表示されたツールチップ
![tooltip](https://user-images.githubusercontent.com/42687608/65820167-d2a0c480-e260-11e9-82bb-777cb7a4ce21.jpg)

**Comment by ShekPS** [comment]
I think the same bug:

reproduce:
1. choose Ming
2. prepare 16 * 1k unit in Beijing (on start, there will be 1 * 16k unit)
3. move mouse to the units and it will crash

![QQ截图20190929150002](https://user-images.githubusercontent.com/26006407/65828111-e03e6480-e2c9-11e9-99bc-a8e32cfe5546.png)

**Comment by matanki-saito** [comment]
デフォルトのフォントはこの問題が発生しません
![image](https://user-images.githubusercontent.com/35730970/65828680-71b4d300-e2d8-11e9-8c09-51164ef69e19.png)

**Comment by matanki-saito** [comment]
明の部隊を16分割するクラッシュしました。同じ問題のようです

**Comment by oooFUNooo** [comment]
デフォルトのフォントでは、ヴェネツィアでもイングランドでもCTDしないことを確認しました。
また、その際のツールチップは、縦幅がゴシックフォントの時よりも短いことを確認しました。
明の部隊は12分割した時点でCTDします。
やはりツールチップの縦幅が一定長を超えることがCTDの条件のようです。
おそらく縦1080px（HD）あるいは縦1024px（2^10）が閾値ではないでしょうか？
なお、解像度を高くしたり低くしても、この閾値は変化しませんでした。

**Comment by matanki-saito** [comment]
done
