### ISSUE TITLE
Incorrect truncation of map texts

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#160]
問題：
本来省略されるべきでないマップ上の名前が省略されている。

再現性：
常に

再現手順：
1444年の国家選択画面でクレタ（エーゲ海の島）、スース（北アフリカの国）を確認する。

原因：
Issue #154 への対策として、文字数が長い時は末尾を「…」とする仕様が導入されたが、
それが誤作動しているものと思われる。

解決策：
上記の原因を修正する。

参考画像：
![SS2](https://user-images.githubusercontent.com/42687608/66732990-fa1aa280-ee98-11e9-8f41-a43c05b3421a.jpg)
![SS1](https://user-images.githubusercontent.com/42687608/66732982-ef600d80-ee98-11e9-9814-b705574ed564.jpg)

**Comment by matanki-saito** [comment]
暫定的に表示部分だけ対処

**Comment by oooFUNooo** [comment]
「Extended Timeline」Modで国名の意図せぬ省略を確認しました。

キューバ（2019年）
![SS1](https://user-images.githubusercontent.com/42687608/67353570-ccff7b80-f58d-11e9-9fd7-9b13061a7f38.jpg)

イスラ・フアナ（1836年）
![SS2](https://user-images.githubusercontent.com/42687608/67353606-e0124b80-f58d-11e9-8775-4f00ce687586.jpg)

**Comment by matanki-saito** [comment]
下記の修正にあるリミットの撤回で改善されることを確認しました。
https://github.com/matanki-saito/EU4dll/commit/8488b5139ede1769bb8a6fe8a8a62868cbc0b9d8

![image](https://user-images.githubusercontent.com/35730970/69008847-791c6280-0992-11ea-9612-3f6958ee4aa5.png)
一方で、英語名の頭に...が発生してしまう問題もあり確認中です。これは画面乱れの対策の副作用のようです
![image](https://user-images.githubusercontent.com/35730970/69008853-8fc2b980-0992-11ea-9b8f-af4251cee421.png)

**Comment by matanki-saito** [comment]
extendedのテキストに0x9が入っていることにより発生する問題だった。フォントを調整して対応するのと未定義文字を0x20にすることで対処。
