### ISSUE TITLE
jamming on map

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/EU4dll#161]
マップがやばい
１）
![2019-10-15_1](https://user-images.githubusercontent.com/35730970/66821851-1ba18a00-ef7e-11e9-919a-9ac7b9dbe7c4.png)

[1444_11_11.zip](https://github.com/matanki-saito/EU4dll/files/3728584/1444_11_11.zip)

２）
![20191015154313_1](https://user-images.githubusercontent.com/35730970/66821912-3b38b280-ef7e-11e9-9912-30d0739d211d.jpg)

[ottomans_wc.eu4.zip](https://github.com/matanki-saito/EU4dll/files/3728589/ottomans_wc.eu4.zip)

**Comment by oooFUNooo** [comment]
私の環境でも1番が部分的に再現しました。

- セーブデータをロードするたびに発生したりしなかったりする。
- 発生条件はまったくの謎。
- 有効にしているModは日本語化Mod1/2とゴシックフォントのみ。

再現時の画像（ケースA：頻繁に発生）
![case1](https://user-images.githubusercontent.com/42687608/66838582-da21d680-ef9f-11e9-8d58-adecf5136b4a.jpg)

再現時の画像（ケースB：一度しか発生せず）
![case2-1](https://user-images.githubusercontent.com/42687608/66838674-0f2e2900-efa0-11e9-8948-c494560c25c7.jpg)
![case2-2](https://user-images.githubusercontent.com/42687608/66838709-210fcc00-efa0-11e9-8492-a8174483d01b.jpg)

**Comment by matanki-saito** [comment]
ロードすると発生しますね。逆に1444年の最初の国選択画面で開始しようとするときは発生しません。

**Comment by oooFUNooo** [comment]
1444年11月11日（デフォルト開始日）のデータなのに、
なぜこのデータだけ不具合が発生するのでしょう？

**Comment by matanki-saito** [comment]
map_view()の処理の問題があるように見える

**Comment by matanki-saito** [comment]
カウント処理に関係する処理としてこの部分は気になる
![image](https://user-images.githubusercontent.com/35730970/66946519-0f0b5780-f08c-11e9-8798-68b87789bf34.png)

**Comment by matanki-saito** [comment]
この画像を再度見る。
![image](https://user-images.githubusercontent.com/35730970/66946519-0f0b5780-f08c-11e9-8798-68b87789bf34.png)

この時、callの引数となるrcx（[rbp-40h]）は表示文字列の構造体へのアドレスになる。
callの中を見よう
![image](https://user-images.githubusercontent.com/35730970/66950355-2bf75900-f093-11e9-8327-b8bbec3d6e80.png)
つまり次の文字を見る

**Comment by matanki-saito** [comment]
最後のcallを見る
![image](https://user-images.githubusercontent.com/35730970/66953060-bbebd180-f098-11e9-988a-70e854d95866.png)
矢印の部分で取得している

**Comment by matanki-saito** [comment]
このループで一つおきに元の文字と別の文字をトグルして表示するように改造した結果、別の文字が0x30（0）や0x40（＠）などでは画面乱れは発生しなかった。一方で0x20（ホワイトスペース）は画面乱れが発生した

**Comment by matanki-saito** [comment]
map_view_proc1をdisableにした状態。
![image](https://user-images.githubusercontent.com/35730970/67144494-f2e8ff80-f2b1-11e9-85df-8a81e87b1f5f.png)

**Comment by matanki-saito** [comment]
proc1_3をコメントアウト
![image](https://user-images.githubusercontent.com/35730970/67146251-3a788700-f2c4-11e9-937c-456f7a216362.png)

**Comment by matanki-saito** [comment]
nudgeモードあたりに問題がありそう。修正ｔｘｔ
[positions.txt](https://github.com/matanki-saito/EU4dll/files/3746942/positions.txt)

**Comment by matanki-saito** [comment]
おそらくだが、修正そのものはしなくてもよさそうでpositions.txtだけでよさそう

**Comment by oooFUNooo** [comment]
positions.txtはチェックサムを変更するので、
鉄人モードやマルチプレイに影響を及ぼすのではありませんか？

**Comment by matanki-saito** [comment]
上記、確認できますか？

**Comment by matanki-saito** [comment]
https://eu4.paradoxwikis.com/Checksum#What_affects_the_Checksum

**Comment by oooFUNooo** [comment]
上記関連部分を引用

> Following files are used for the checksum calculation:
> 
> - map:
> all .txt, .map,.csv and .bmp files

**Comment by matanki-saito** [comment]
nudgeモードが怪しいと踏んだわけだが、過去にnudgeモードに関連した修正のissueは下記。
https://github.com/matanki-saito/EU4dll/issues/12

![image](https://user-images.githubusercontent.com/35730970/67154927-f2e31100-f33e-11e9-8171-18df3248cd66.png)

この修正箇所はmap_view()のprocの呼び出し元のうちの一つ。もう一つはmap_adjustmentにつながっている

**Comment by matanki-saito** [comment]
提供されたデータの中で唯一再現性があるもの。

[bizanzu.eu4.zip](https://github.com/matanki-saito/EU4dll/files/3828743/bizanzu.eu4.zip)

**Comment by matanki-saito** [comment]
なんとなく、こいつが悪い気がする。これは昔も問題を起こしていた（文字が長すぎる）
![image](https://user-images.githubusercontent.com/35730970/68964110-e0fc6d00-081b-11ea-8f12-8f0c3a67205f.png)

**Comment by matanki-saito** [comment]
いろいろ試した結果次のような感じと推定。
 - プロビンス名用のバッファには47文字までしか入らない（仕様）
 - 長すぎる文字列だと、下記のように中途半端に切れてしまう
  ![image](https://user-images.githubusercontent.com/35730970/69003438-64fe4400-0945-11ea-83fd-96c0b465afce.png)
 - ただし、なぜか0x10が0x01などになってしまっている。
 - 0x01のフォントを読みだそうとして失敗している？

**Comment by matanki-saito** [comment]
下記は今回やっていて見つけた、国と地域名を結合する処理。
![image](https://user-images.githubusercontent.com/35730970/69003449-aabb0c80-0945-11ea-8249-5eccd9f7867a.png)
見つけるには下記のパターンで検索すると見つかる。
```
4C 8D 05 ? ? ? ? 48 8D 55 78 48 8D 8D 40 01
```
セパレーターを＠＠に変えると下記のようになる。
![image](https://user-images.githubusercontent.com/35730970/69003458-cfaf7f80-0945-11ea-9c4c-1da058998c27.png)

**Comment by matanki-saito** [comment]
上記でいったん対応
