### ISSUE TITLE
Enhancement on regional names

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#164]
問題：
オプション「飛び地に地域名を使用」を有効にすると、
国名と地域名がスペースで連結され、不自然な地名が表示される。
例）「モンゴル モンゴル」

原因：
日本語化の都合上、国名の形容詞形には名詞形と同じ訳が使用されており、
国名が地域名と直接連結されることで、不自然な地名となっている。

解決策：
Issue #161 で技術的な可能性が示された手法を応用し、
国名と地域名のセパレーターをスペースから「領」などの文字に変更する。

解決策の問題点：
上の解決策を単純に適用すると、英語版でも他のマルチバイト言語版でも
セパレーターが「領」になってしまう。

**Comment by matanki-saito** [comment]
教皇領だと「教皇領領プロヴァンス」になりますね

**Comment by matanki-saito** [comment]
とりあえず完了とします
