### ISSUE TITLE
Error when save file

### ISSUE THREAD

**Issue by ShekPS** [matanki-saito/EU4dll#166]
Hi, I had an error when saving file. I reproduced it also with the Japanese Mod.

1. Create a custom nation in Taiwan, the name is ケラン, same as the province name.
![QQ截图20191125214922](https://user-images.githubusercontent.com/26006407/69545963-c79eb200-0fcd-11ea-8f4e-ea257f1f34e2.png)
2. Save the game with "TaiwanTest1", it is OK at this point.
3. Try to overwrite the save.
![QQ截图20191125215008](https://user-images.githubusercontent.com/26006407/69545944-ba81c300-0fcd-11ea-80e9-14c0978f7e4c.png)
4. It says error
![QQ截图20191125215015](https://user-images.githubusercontent.com/26006407/69545957-c40b2b00-0fcd-11ea-9f90-3b2382818cea.png)

5. I can still save the game with the generated name "ケラン1444_11_11"
![QQ截图20191125215405](https://user-images.githubusercontent.com/26006407/69546188-367c0b00-0fce-11ea-99ea-00cc947ab397.png)
6. When I try to overwrite it, after click the save, the name becomes corrupted
![QQ截图20191125215600](https://user-images.githubusercontent.com/26006407/69546260-62978c00-0fce-11ea-8db2-42670151867a.png)

Guess there is something wrong with the save name processing, even if it's all English...
I'm using the latest release (Build: 20191119.1)

**Comment by matanki-saito** [comment]
Let me confirm

**Comment by matanki-saito** [comment]
未実装でした
https://github.com/matanki-saito/EU4dll/issues/89
