### ISSUE TITLE
CTD on mouse over a save data includes the specific character

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#169]
問題：
直前のセーブデータに「大」が含まれるとコンティニューボタンでCTDが発生する。

再現性：
常に

再現手順：
1. 1444年の大越（現在のベトナム北部にある国）で開始。
2. メニューからセーブする（ファイル名は編集しない）
3. メインメニューに戻る（一度終了しても結果は変わらない）
4. 直前のセーブデータをロードするボタンにマウスカーソルを乗せるとCTD発生。

原因：
UTF-8における「大」の文字コードはASCIIの「å¤§」に相当する。
¤と§はともにEU4において特別な意味を持つ文字であるが、
これらの文字がエスケープされないままファイル名表示ルーチンに渡されている。
（具体的には§が原因だと推測される）

参考画像：
矢印のボタンにマウスカースルを乗せるとCTDする。
![CTD](https://user-images.githubusercontent.com/42687608/71520818-59694a00-2901-11ea-8672-19b63f1623b4.jpg)

**Comment by matanki-saito** [comment]
確認します

**Comment by matanki-saito** [comment]
done
![image](https://user-images.githubusercontent.com/35730970/71721443-70abb880-2e68-11ea-91e5-03aefa76f690.png)
