### ISSUE TITLE
Truncated overseas province name

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/EU4dll#182]
When owning a overseas province, like if you are Japan owning a province in Sakhalin, the correct state name should be '日本-萨哈林', yet it's displayed as '日本 -萨哈', the last letter is truncated, and there seem to be an extra space before the dash.

![image](https://user-images.githubusercontent.com/8399711/74798913-0e205600-530a-11ea-9d0c-6c5f8a6e573d.png)

**Comment by matanki-saito** [comment]
thx, I will check my code

**Comment by ShekPS** [comment]
This occurs when the specified SEPARATE_CHARACTER_CODE_POINT not exist in your font.
The default one is Japanese 領 which is not in the Chinese font.

**Comment by bruceCzK** [comment]
Thanks. After changing the option in plugin.ini, it's ok now. I think I'll edit this file in the zip file before it's released to our subscribers.

![image](https://user-images.githubusercontent.com/8399711/74898453-e21dd700-53d4-11ea-8e00-7f1c745e3bfc.png)

**Comment by nieyuanhong** [comment]
Maybe you can open file ".\plugins\plugin.ini", and modify all its contents 
```ini
[options]
ERROR_TEST=no
;whitespace=32, 領=38936, 屬=23660, 령=47161
SEPARATE_CHARACTER_CODE_POINT=32
REVERSING_WORDS_BATTLE_OF_AREA=yes
```
like this

![one](https://user-images.githubusercontent.com/19494884/75387195-ec345e00-591d-11ea-855c-0181470ca14f.png)

**Comment by matanki-saito** [comment]
Sorry for my late reply
1.29 Dll has new feature to change the separated character
Function can be controlled by modifying the INI file
