### ISSUE TITLE
1.31.4 was available to public beta player, Could you please update the dll to this version?

### ISSUE THREAD

**Issue by ZSJsts** [matanki-saito/EU4dll#205]
Although the default automatic update will not update it 

but player can use code H2o2jKP4YsMOiuCx  to choice thus version
 (https://forum.paradoxplaza.com/forum/threads/eu4-1-31-4-majapahit-public-beta-is-now-available-for-opt-in.1474828/)

I don't know why they haven't released it yet, but this version works very well. It fixes all the known issues (I guess they are worried about failing again and delayed the release of the update)

Could you please update the dll to this version?

**Comment by matanki-saito** [comment]
OK , I'll fix it tonight

**Comment by ZSJsts** [comment]
> OK , I'll fix it tonight

やったー!

**Comment by matanki-saito** [comment]
Done !
https://github.com/matanki-saito/EU4dll/releases/tag/30
