### ISSUE TITLE
1.31.5 beta is updated,thank you

### ISSUE THREAD

**Issue by wuqiwustci** [matanki-saito/EU4dll#207]
https://forum.paradoxplaza.com/forum/threads/eu4-1-31-5-majapahit-beta-now-available-for-opt-in.1479711/
Enter the following password in the beta access code field: 384ccRX3VnyRjf7q - then click "Opt into: 1.31.5"

**Comment by wuqiwustci** [comment]
https://forum.paradoxplaza.com/forum/threads/eu4-1-31-5-majapahit-beta-now-available-for-opt-in.1479711/
 Enter the following password in the beta access code field: 384ccRX3VnyRjf7q - then click "Opt into: 1.31.5".

**Comment by matanki-saito** [comment]
Thank you. I will check it
