### ISSUE TITLE
Release 36 on v1.31 getting "Multibyte DLL hasn't supported this game version yet"

### ISSUE THREAD

**Issue by vicch** [matanki-saito/EU4dll#213]
- Win10
- EU4 v1.31.0.0
- steam_EU4_1.31_fixdll_build_36.zip

Getting "Multibyte DLL hasn't supported this game version yet" on launch. Is the version 1.31 not supported? I don't seem to find version support info but the repo home page says "master:1.31.5.2" so I assume it's supported.

Thank you.

**Comment by matanki-saito** [comment]
Yes, 1.31.0.0 is not supported. 
Support version is following
![image](https://user-images.githubusercontent.com/35730970/129443047-77516e98-9fc5-4200-b5d6-75dfb61d254c.png)
