### ISSUE TITLE
Strange Conflict with Citrix

### ISSUE THREAD

**Issue by ShekPS** [matanki-saito/EU4dll#218]
After install Citrix, I can't start the game from steam, dowser.exe failed to run.
I can run it only after deleting the version.dll.

The crash dump is like this, it seems related to Citrix (a software my company uses for remote work) 
![图片](https://user-images.githubusercontent.com/26006407/138516421-189d37a1-793d-47a1-a935-071d164a52e4.png)

The crash dump file:
[dowser.exe.4580.zip](https://github.com/matanki-saito/EU4dll/files/7401108/dowser.exe.4580.zip)

You can download citrix from their website
https://www.citrix.com/en-gb/products/receiver.html

**Comment by ShekPS** [comment]
> @ShekPS I created d3d9.dll instead of Version.dll. [d3d9.zip](https://github.com/matanki-saito/EU4dll/files/7426827/d3d9.zip)
> 
>     1. Remove Version.dll from eu4.exe directory
> 
>     2. Put a d3d9.dll into the eu4 directory.
> 
>     3. Check if the game can be launched from the launcher.

I think I have found the solution.

I change the code of version.dll like this:
![图片](https://user-images.githubusercontent.com/26006407/150639899-be5233c7-1af7-40db-a287-fba121efc032.png)

I think it's because the paradox launcher (or citrix) is using one of the functions in hook.asm, but the initial value of those function pointer is null, so you still need to call initInjector() even if it's not eu4.exe, otherwise it tries to call a null function pointer and will crash.

**Comment by matanki-saito** [comment]
Nice ! Thank you ! I will implement this code
