### ISSUE TITLE
NO SUPPORT VERSION

### ISSUE THREAD

**Issue by yoooooolx** [matanki-saito/EU4dll#221]
"Multibyte DLL hasn't supported this game version yet. Do you want to start a game?"
I am using release 41, and yesterday it works fine. But today after a small game update it reports this warning and I cannot enter the game with translation mod anymore.

**Comment by matanki-saito** [comment]
Please wait for about 30~40 minutes.

**Comment by matanki-saito** [comment]
New release !
https://github.com/matanki-saito/EU4dll/releases/tag/42

**Comment by yoooooolx** [comment]
Thank you sincerely!
