### ISSUE TITLE
Patch Update When?

### ISSUE THREAD

**Issue by Tachibana-Rui** [matanki-saito/EU4dll#223]
EU4 1.33_beta was released, and the patch pops out a window while the game is loading, saying "game version not supported". 
Your patch is a vital part of the localization mods. We appreciate your great work and looking for the patch update.

**Comment by matanki-saito** [comment]
Thanks for sharing the information, I will work on it on 2/6.

**Comment by matanki-saito** [comment]
Check the new release !
https://github.com/matanki-saito/EU4dll/releases/tag/43

**Comment by matanki-saito** [comment]
Check Version 44 please !
https://github.com/matanki-saito/EU4dll/releases/tag/44

**Comment by Gumiaya** [comment]
the 44version say no support version

**Comment by matanki-saito** [comment]
hmm , I will check it

**Comment by matanki-saito** [comment]
Sorry. DLL automatic update system database was not updated. Updated now. Please try to start the game again.

**Comment by Gumiaya** [comment]
ty happy valentine!
