### ISSUE TITLE
CTD on a long tooltip

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#226]
問題：
画面からはみ出すほど上下に長いツールチップが表示されると、その数秒後にクラッシュする。

再現性：
常に

再現手順：
以下、[Extended Timeline](https://steamcommunity.com/sharedfiles/filedetails/?id=217416366) 1.13.4および[同日本語版](https://steamcommunity.com/sharedfiles/filedetails/?id=1889254486)を前提とする（更新日はいずれも2022/02/25）。

1. 西暦58年のブックマーク「パルティア戦争」を選択する（デフォルト）
2. ローマを選択してプレイを開始する
3. 開始時からパルティアほか数カ国と戦争中なので、適当に時間を進めて和平する（無条件降伏で良い）
4. 国家の決断（decision）から「ローマの分割」を実行する（戦争中は実行できない）
5. 時間を1日進めるとイベント「ローマの分割」が発生する（参考画像）
6. 選択肢にカーソルを合わせると巨大なツールチップが表示され、その数秒後にクラッシュする

原因：
不明
日本語化DLLがインストールされていても英語環境（日本語化MODなし）では発生しない。

解決策：
不明

参考画像：
![20220225090647_1](https://user-images.githubusercontent.com/42687608/155686886-affb14cf-8742-433f-8ca2-4d1fd508007f.jpg)

**Comment by matanki-saito** [comment]
_alloca_probeで落ちているようでした。
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170
日本語だと文字数は英語の３倍の長さになるので、おそらく想定より超えてしまったのではないかと思われます

**Comment by matanki-saito** [comment]
DLLで治せるか怪しくなってきたので一旦回避策を書きます。
１）うさみみハリケーンをダウンロードします。
https://www.vector.co.jp/soft/win95/prog/se375830.html
２）UMPE64.exeを開きます。PEエディタを起動して編集を選びます。
<img width="613" alt="image" src="https://user-images.githubusercontent.com/35730970/155725002-6e018c06-c4b5-419c-8d58-48b5e08d7a81.png">
３）EU4.exeをD&Dします。
<img width="731" alt="image" src="https://user-images.githubusercontent.com/35730970/155725179-2054277d-259f-43d4-912b-3a142b7fdff8.png">
４）StackReserveのサイズを000000400000から000001400000に、StackCommitサイズを000000001000から000000004000にして、書き込みします。
<img width="613" alt="image" src="https://user-images.githubusercontent.com/35730970/155725305-b3e23ebd-de65-44b3-9f81-e95aa7803d1d.png">
