### ISSUE TITLE
Mod do not support the latest update 1.33.3

### ISSUE THREAD

**Issue by kalvin807** [matanki-saito/EU4dll#228]
Hi, the current do not support the latest hotfix version released recently.  [patch note](https://store.steampowered.com/news/app/236850/view/3209385828889060994)

I was attempted to submit a PR to update it but I am stuck in a error that I fail to fix.
Here is my hacky attempt and hope they are helpful for you. :)

1.  I added `minor` version 333 to function `GetVersionFromExe` to return `v1_33_0_0`
2.  When I run the game with my patched dll, the plugins return error and prompted popup saying patch do not support this game version yet

Log output: https://pastebin.com/hsYAReay

Since the error report MapView has problem, I suspect the update also did some change to this part which fail the binary search?

I am running the develop version x64 forked from branch `develop`

**Comment by matanki-saito** [comment]
Thanks for the report!
I had a busy schedule on Thursday and Friday, so I skip the fix sorry.
I will work on Saturday and Sunday!
thank you!

**Comment by matanki-saito** [comment]
Please check it !
https://github.com/matanki-saito/EU4dll/releases/tag/49

**Comment by kalvin807** [comment]
It works! Thanks for the work
ありがとうございます！
