### ISSUE TITLE
Windows detected virus

### ISSUE THREAD

**Issue by snowdrop123** [matanki-saito/EU4dll#234]
![image](https://user-images.githubusercontent.com/113912278/191025866-14d80680-7676-4bd7-9b32-8471528f791b.png)
Why Windows detected virus in 「steam_EU4_fixdll_build_56.zip」.I'm delete and downloading several times but it show same thing to me. Could you check this file to find the issue in it? Thank you.

**Comment by matanki-saito** [comment]
Sorry for the inconvenience.
The project's version.dll hasn't been updated for a long time, so it's possible that many people tried to rewrite it all at once and Microsoft decided it was a problem.

**Comment by matanki-saito** [comment]
As a work-around, extract version.dll from the old Zip file and use it instead.

https://github.com/matanki-saito/EU4dll/releases/tag/53

**Comment by snowdrop123** [comment]
I think my problem been solved. Thanks your replay.
