### ISSUE TITLE
Release 57 not working

### ISSUE THREAD

**Issue by Malatan** [matanki-saito/EU4dll#236]
It still gives the "Multibyte DLL hasn't supported this game version yet" message.

**Comment by matanki-saito** [comment]
let me check

**Comment by matanki-saito** [comment]
The Multibyte DLL is automatically updated, and it takes effect slightly later than Release. I think it can be activated now.

If it doesn't, try removing  `C: \Program Files (x 86) \Steam \steamapps \common \Europa Universalis IV \plugins \Plugin 64 .dll`. The latest version is automatically downloaded after starting EU4.

**Comment by Malatan** [comment]
It works now, thx again for the response. ^^
