### ISSUE TITLE
eu4_profiling support? 

### ISSUE THREAD

**Issue by 1onepower** [matanki-saito/EU4dll#238]
Cite from wiki: 

> Since patch 1.23, Europa Universalis IV includes a performance profiler alongside the normal game. This tool is useful for modders that want to measure and diagnose poor performance within their mods.
> 
> To use the profiler, you need to launch the game launcher by click eu4_profiling.exe within the game installation folder. This will launch the game with whatever mods you had selected previously in the launcher. In other words, if you wish to test the performance of the game with mods enabled, be sure to enable these mods before launching eu4_profiling.exe.
> 
> Once in game, allow the game to run until you have reached a suitable duration, and then open the console and type dump_script_profiling to write to the profiling.log in the logs folder.

Can you please support double-byte characters with eu4_profiling.exe as well? Thanks!

**Comment by matanki-saito** [comment]
Hello!
It's theoretically possible, but I need to look at a lot from scratch, and it's not likely to happen anytime soon...
