### ISSUE TITLE
how can i uninstall it?

### ISSUE THREAD

**Issue by CURRENTF** [matanki-saito/EU4dll#243]
As long as I open the Tianyi network disk（天翼网盘） to install the application, it will trigger an error that eu4dll does not support the current game version

**Comment by CURRENTF** [comment]
I have uninstalled eu4 on steam, but the error window still pops up

**Comment by matanki-saito** [comment]
There have been no reports so far of network disk causing problems, but I can tell you how to completely remove it.

To completely remove the EU4dll, delete the version.dll and plugins folders in the game directory.

<img width="754" alt="image" src="https://github.com/matanki-saito/EU4dll/assets/35730970/4577acec-1e60-404a-86d4-7efc3f728682">

The game directory is usually found below methods.
 - https://www.motionews.com/post/how-to-locate-files-on-steam-in-2022
