### ISSUE TITLE
The latest release(67) no longer supports the newest updated version(reported on 2023-06-20, version 1.35.4)

### ISSUE THREAD

**Issue by gykxjtu** [matanki-saito/EU4dll#244]
An update was triggered in June.20, 2023, after which a prompt dialog box says that the multibyte patch does not support the current version of EU4.

Should I clone this repo and compile it myself or wait for the next stable tagged release?

**Comment by gykxjtu** [comment]
An update was triggered in June.20, 2023, after which a prompt dialog box says that the multibyte patch does not support the current version of EU4.

**Comment by matanki-saito** [comment]
Fix it!

**Comment by gykxjtu** [comment]
It works! 
Thx!
