### ISSUE TITLE
Dll causeing some mods' custom tooltip UI displayes messly

### ISSUE THREAD

**Issue by nsYW** [matanki-saito/EU4dll#246]
問題：
**Meiou & Taxes** modでは、カスタムツールチップのフレームの幅が狭くなりました。

再現性：
常に

再現手順：
問題は [Meiou & Taxes 3.0](https://steamcommunity.com/sharedfiles/filedetails/?id=2630437525) で発生します。
  エリアバーのカスタムツールチップの上にマウスポインタを置くと、フレームの幅がバニラ（DLLをインストールする）よりも狭くなり、UI全体で異常な改行が発生することに気づくでしょう。
    
原因：
不明
dllをインストールした後、バニラ英語環境でも問題が発生します。

解決策：
不明

参考画像：
![1_c](https://github.com/matanki-saito/EU4dll/assets/24467602/fef1f92f-02e8-4492-83e9-882889461db4)
![2_c](https://github.com/matanki-saito/EU4dll/assets/24467602/f3fae83a-2115-484b-90f1-7efbc4526c33)

**Comment by matanki-saito** [comment]
確認します

**Comment by matanki-saito** [comment]
dllで問題になっている箇所を修正しました
