### ISSUE TITLE
1.36.0.0 Released on Nov.7, 2023.

### ISSUE THREAD

**Issue by gykxjtu** [matanki-saito/EU4dll#247]
Hi, EU4 1.36.0.0 was released today.
Will you please make a new release of multibyte patch?
Thx.

**Comment by JunxiHe459** [comment]
Seconded. Thank you so very much!

**Comment by matanki-saito** [comment]
Hello. Due to the lack of time available during the week, we will be responding this Saturday and Sunday.

**Comment by gongjuecloak** [comment]
very six
