### ISSUE TITLE
[1.37 bug report] Text floating out of the Box

### ISSUE THREAD

**Issue by YouCaiJun98** [matanki-saito/EU4dll#257]
Hello author, thanks for developing the patch :) Had countless wonderful moments with EU4 thanks to your effort XD
When playing with the newest release, I came across the following issue, that the Chinese texts floating out of the box, like
![screenshot](https://github.com/matanki-saito/EU4dll/assets/48440749/a91d26f4-302b-4109-a178-887c4541058e)
I wonder if it was caused by the patch. Could you have a look at it if convenient? Many Thanks! :)

**Comment by matanki-saito** [comment]
Thank you for your report.
I understand this problem and it seems that there is a problem with the 1.36-2 string omission process porting.
Currently, I haven't found where the bug is yet...

**Comment by matanki-saito** [comment]
Fix it!
