### ISSUE TITLE
Lost Chinese characters while loading saved games

### ISSUE THREAD

**Issue by a2825295343** [matanki-saito/EU4dll#258]
When loading saved games the Chinese characters cannot be shown correctly. Would you please fix the bug？
![图片1](https://github.com/matanki-saito/EU4dll/assets/62547847/da2a6a51-72b8-4971-9b33-6e218c42f62b)

**Comment by matanki-saito** [comment]
ok let me check it

**Comment by matanki-saito** [comment]
Fix it : https://github.com/matanki-saito/EU4dll/releases/tag/85

**Comment by a2825295343** [comment]
UR my hero！

**Comment by a2825295343** [comment]
OH bad news: the shown words are correct now, but the saved games cannot be loaded normally now.

**Comment by matanki-saito** [comment]
hmm, sorry. let me re-check

**Comment by matanki-saito** [comment]
new release: https://github.com/matanki-saito/EU4dll/releases/tag/86
please check 🙏

**Comment by a2825295343** [comment]
Perfectly fixed！Thanks 4 ur contribution！(^o^)/
