### ISSUE TITLE
The reason for the institution's growth cannot be displayed

### ISSUE THREAD

**Issue by fvcymzs** [matanki-saito/EU4dll#264]
In the new version, the reason for the institution's growth cannot be displayed, there is only a colon.
![1](https://github.com/user-attachments/assets/ca9f25a3-a2e3-477e-b827-496c7796a286)

**Comment by matanki-saito** [comment]
Thank you for your report. I will revert once

**Comment by fvcymzs** [comment]
The problem has been solved, thanks for the update!
