### ISSUE TITLE
Virus detected when downloading by google chrome

### ISSUE THREAD

**Issue by ABravoCode** [matanki-saito/EU4dll#266]
Dear author, when I use Chrome to download the zip file of Release92, it shows:

![829c4e5cd027693b3af90e8a7a1146a0](https://github.com/user-attachments/assets/7e1242db-ff09-4ca6-9bc1-618aaa378db6)

Is this problem caused by some settings in the file itself? Or is there any solution?

Looking forward to your reply.

**Comment by matanki-saito** [comment]
Report thank you

The changes from v91 to v92 are only as follows, and there is no virus related.
https://github.com/matanki-saito/EU4dll/pull/265/files

 A problem was found in v91, so we fixed it.
https://github.com/matanki-saito/EU4dll/issues/264

It seems that virus detection is detected by Windows Defender. 
I will now submit the dll to Microsoft. 

https://www.microsoft.com/en-us/wdsi/filesubmission

Please wait until the dll registered in Microsoft's DB.

**Comment by matanki-saito** [comment]
Checking status

https://www.microsoft.com/en-us/wdsi/submission/cf4bcf4d-0597-428e-a395-628740189307

**Comment by matanki-saito** [comment]
https://www.microsoft.com/en-us/wdsi/submission/c7ae556b-7e6a-4f37-98e8-da7e1bbf2279

**Comment by ABravoCode** [comment]
Noted with thanks. 

Unfortunatly I'm not authorized to view details for the requested submission on your registered file. 

I will wait for its registration to be completed and close this comment. :D

**Comment by matanki-saito** [comment]
It seems that the zip file is reacting to virus detection, not the contents.
I created the zip file on my PC. Please use this one.

https://github.com/matanki-saito/EU4dll/releases/tag/92

**Comment by ABravoCode** [comment]
Thank you for identifying the issue and resolving it. Now I can download normally.
