### ISSUE TITLE
Colonial text on the map garbling

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/EU4dll#35]
インド沿岸でも起きる
![image](https://user-images.githubusercontent.com/35730970/45960180-9687c200-c056-11e8-8825-33aa7134986a.png)

**Comment by matanki-saito** [comment]
これは見つけたときのセーブデータが無いとちょっと難しいのでClose

**Comment by matanki-saito** [comment]
同様の症状の報告ありのためreopenした。セーブデータの提供あり

**Comment by matanki-saito** [comment]
[eu4eng.zip](https://github.com/matanki-saito/EU4dll/files/2962029/eu4eng.zip)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
どうもこれらの文字は、セーブデータに含まれておらず、動的に作られているらしい。
![image](https://user-images.githubusercontent.com/35730970/54295264-05051000-45f6-11e9-8e52-917343382067.png)

**Comment by matanki-saito** [comment]
どうもmalaya_regionが原因っぽい。これをmalayaにすると英語で表示される

**Comment by matanki-saito** [comment]
とりあえず一文字スペースを入れると直る。

**Comment by matanki-saito** [comment]
おそらく、MINGとMALAYAを結合する処理で問題が発生している？

**Comment by matanki-saito** [comment]
文字数の関係？
![image](https://user-images.githubusercontent.com/35730970/54301807-025ce780-4603-11e9-8fe3-b4a4fa5c86cd.png)

**Comment by matanki-saito** [comment]
マだけにするとこんな感じになる。
![image](https://user-images.githubusercontent.com/35730970/54302020-6d0e2300-4603-11e9-9481-42c2c0ecd1c4.png)

**Comment by matanki-saito** [comment]
どんなエスケープ文字でも「日」や「０」になってしまう…

**Comment by matanki-saito** [comment]
map-adjustmentをコメントアウトしたらこんな感じになった
![image](https://user-images.githubusercontent.com/35730970/65888112-f4718700-e3d9-11e9-817d-53baa05996e7.png)

**Comment by oooFUNooo** [comment]
まだセーブデータを検証していないので完全に推測で申し上げますが、
この現象は1.29におけるオスマンの文字化けと酷似しているように思われます。
あちらの原因はEU4が自動的に挿入する半角スペースでした。
こちらの場合も特定の条件下で名前に半角スペースが挿入されている可能性はないでしょうか？
5月14日のコメント「一文字スペースを入れると直る」もそれを示唆しているように思われます。

**Comment by matanki-saito** [comment]
問題と思っている箇所の下に、下記がいるので、合わせて調査しています。
https://github.com/matanki-saito/EU4dll/issues/154

**Comment by matanki-saito** [comment]
うまくいくが、だめになるところがある
![image](https://user-images.githubusercontent.com/35730970/65987749-6b357f80-e4c1-11e9-9382-c7c041f108df.png)

**Comment by matanki-saito** [comment]
メモ：
ループの最初：
![image](https://user-images.githubusercontent.com/35730970/65987810-8a341180-e4c1-11e9-8cbe-df37f5b714d7.png)
ループの真ん中：いろいろ直しているところ
![image](https://user-images.githubusercontent.com/35730970/65987845-9cae4b00-e4c1-11e9-83b0-bf1d76794065.png)
ループの後半：
![image](https://user-images.githubusercontent.com/35730970/65987881-af288480-e4c1-11e9-9468-b9a4cd5000b8.png)

**Comment by matanki-saito** [comment]
ループの後半は怪しく、ループの真ん中と同じように、3バイト扱いで見る必要があるはず。
あと、lea eax, [rcx -1 ]で位置文字前を見るようにしていると思うが、まだよくわかってないのでちゃんと確認する

**Comment by matanki-saito** [comment]
["あ","い","う"].join(" ")をforでやってるから2段になっている

**Comment by matanki-saito** [comment]
左のルートはスペースの挿入が足りなかったので、スペースを一つ増やして再度実行
![image](https://user-images.githubusercontent.com/35730970/66066645-de53fa00-e584-11e9-9261-bf4d91ba5542.png)
右のルートはスペースが挿入が大丈夫だったので終了

**Comment by matanki-saito** [comment]
わからん。一旦このブロック全体をスキップするように改造して変化があるか見る

**Comment by matanki-saito** [comment]
スキップするとこうなる。
![image](https://user-images.githubusercontent.com/35730970/66146064-fbe99800-e646-11e9-96f1-61ff4f156c19.png)

**Comment by matanki-saito** [comment]
リージョン名のBRITISHをトリガーしやすくB'Rなどと変えたとき、マップ文字はこんな感じになる
![image](https://user-images.githubusercontent.com/35730970/66152837-496d0180-e655-11e9-99af-ad9c44c3e267.png)

**Comment by matanki-saito** [comment]
伸ばしが足りないとスペース(0x20)がどんどんふえていく
![image](https://user-images.githubusercontent.com/35730970/66153169-f6e01500-e655-11e9-9606-983d17c3f2d0.png)

**Comment by matanki-saito** [comment]
あーやっとわかった。一時的な変数の[rbp + 1F0h - 1F0h]に3バイト入れて、次にスペースなどが来ても0クリアされていないから、ループが回ってしまい、rbxが不当にカウントされていた。
![image](https://user-images.githubusercontent.com/35730970/66218509-49780a80-e704-11e9-8365-b4233b6cd522.png)

![image](https://user-images.githubusercontent.com/35730970/66218482-39f8c180-e704-11e9-92c4-c300188a4f26.png)
