### ISSUE TITLE
マップ上の文字が全体的に小さくなっている

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#45]
問題：
マップ上に表示される文字（国名など）が、以前のバージョンと比較して小さくなっている。

再現性：
常に

再現手順：
v1.26とv1.27で、それぞれプレイ国家選択画面のスクリーンショットを撮り、比較する。
日本語化MOD標準のフォントでは違いがわかりにくいので、適当なMODでフォントを大きくすると良い。

原因：
不明

解決策：
不明

参考画像：

v1.26（けいふぉんと）
![ss1 26-1](https://user-images.githubusercontent.com/42687608/46574335-87046380-c9dc-11e8-9a7c-9bfa628c7c9f.jpg)

v1.27（けいふぉんと）
![ss1 27-1](https://user-images.githubusercontent.com/42687608/46574340-95eb1600-c9dc-11e8-9819-930f3efa4cd7.jpg)

v1.26（標準フォント）
![ss1 26-2](https://user-images.githubusercontent.com/42687608/46574346-a9967c80-c9dc-11e8-8155-bf1693945ee2.jpg)

v1.27（標準フォント）
![ss1 27-2](https://user-images.githubusercontent.com/42687608/46574351-b6b36b80-c9dc-11e8-989f-1e5f29a5d3ec.jpg)

**Comment by oooFUNooo** [comment]
補足：
漢字はサイズが変わらずに文字と文字の間が広くなる模様。

**Comment by matanki-saito** [comment]
多分下記の問題と関係ありますね。
https://github.com/matanki-saito/EU4dll/issues/41

了解ですー 👌

**Comment by matanki-saito** [comment]
よく見るとオスマンは変わってないなぁ。なんでだろ

**Comment by matanki-saito** [comment]
https://github.com/matanki-saito/EU4dll/pull/48

**Comment by matanki-saito** [comment]
解消しましたのでcloseします
