### ISSUE TITLE
イベントダイアログの縦幅が長すぎる

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#46]
問題：
イベント発生時に表示されるダイアログの縦幅が不自然に長くなっている。

再現性：
頻繁

再現手順：
イベントの文章が長いほど確認が容易になる。典型的なのはルネサンスなどの制度発祥イベント。

原因：
不明
おそらく文字幅の計算に失敗しているものと推測される。

解決策：
不明

参考画像：
以下の画像はまったく同じ条件で撮影したものではありませんが、同じイベントです。
v1.26の方はトリミングしたサイズの小さい画像であることに注意してください。

v1.26
![dialog1 26](https://user-images.githubusercontent.com/42687608/46574935-ce8fed00-c9e6-11e8-9466-5d7e6c46ea1f.jpg)

v1.27
![dialog1 27](https://user-images.githubusercontent.com/42687608/46574938-da7baf00-c9e6-11e8-9b32-c0a74e110d99.jpg)

**Comment by matanki-saito** [comment]
https://github.com/matanki-saito/EU4dll/pull/48

**Comment by matanki-saito** [comment]
解消しましたのでcloseします
