### ISSUE TITLE
州の上に表示される黄色いテキストの文字化け

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#50]
問題：
要塞を包囲している時などに州の上に表示される黄色いテキストが文字化けしている。

再現性：
常に

再現手順：
適当な条件で要塞を包囲してスクリーンショットを撮影する。
例えば、1444年開始のオスマンでコンスタンティノープルを包囲するなど。
1600年の徳川など、開始時から戦争状態にある国を選ぶと1年待つ手間が省ける。

原因：
不明

解決策：
不明

補足：
日本語以外の英数字は文字化けしない模様。
例えば、要塞のない州を占領中に毎月表示される略奪額は文字化けしていない。

参考画像：
1枚目の画像以外はフォントを変更するMODが入っていますが、同様の症状です。
表示されているテキストが異なるので、参考として掲載します。

日本語化MOD標準フォント
![ss1](https://user-images.githubusercontent.com/42687608/46577961-73351d80-ca2d-11e8-86fc-cf3579e572ed.jpg)

自作のフォント変更MOD使用
![ss2](https://user-images.githubusercontent.com/42687608/46577968-8647ed80-ca2d-11e8-857a-67a0f575af73.jpg)

自作のフォント変更MOD使用＋英語環境のセーブデータを日本語環境でプレイ（最初に発見した時の状況）
![ss3](https://user-images.githubusercontent.com/42687608/46577975-b2636e80-ca2d-11e8-8b5e-b929ba010a50.jpg)

**Comment by matanki-saito** [comment]
下記の酒精漏れか、
https://github.com/matanki-saito/EU4dll/blob/develop/Plugin/Popup.cpp
1個残っている部分っぽいですね
https://github.com/matanki-saito/EU4dll/issues/43
