### ISSUE TITLE
特定のセーブデータ名でCTD

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#58]
問題：
特定のセーブデータ名でCTDが発生する。

再現性：
常に

再現手順：
1. 1444年のビザンツで開始。
2. オプションから即セーブを試みる。
3. セーブデータ名は表示される「ビザンツ1444_11_11」のまま。
4. CTD発生。

原因：
不明。
本日未明のアップデートでエンバグした可能性が高い。

解決策：
不明

補足：
日本語化MODプロジェクトの不具合報告掲示板に同様の報告あり。
https://paradoxian-japan-mod.com/2018/09/10/post-90/

参考画像：
この状態でセーブをクリックすると確実にCTD発生。

![ss](https://user-images.githubusercontent.com/42687608/46596935-0dbe5b00-cb19-11e8-8876-9b17b8166592.jpg)

**Comment by matanki-saito** [comment]
ここっぽい
![image](https://user-images.githubusercontent.com/35730970/46597406-ed8f9b80-cb1a-11e8-93af-050e531eac01.png)

**Comment by matanki-saito** [comment]
PHYSFS_utf8FromUcs2をフックし忘れてた

**Comment by matanki-saito** [comment]
間違ってmasterにマージ(ヽ'ω`)

**Comment by matanki-saito** [comment]
done
