### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#66]
問題：
日付の表記順が「年月日」ではなく「日月年」または「月年」になっている。

再現性：
常に

再現手順：
1. 適当な国でプレイを開始し、セーブしたのち終了する。
2. メインメニューに戻ると、セーブデータの日付が表示される。

原因：
不明

解決策：
CK2dllのIssue #38が参考になる可能性あり。

参考画像：
上記再現手順の例。ゲーム中ではこれ以外にも至る所に「日月年」または「月年」表記が出現する。

![date](https://user-images.githubusercontent.com/42687608/47695126-e94f2d80-dc43-11e8-9142-a0b59c971877.png)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
参考
https://github.com/matanki-saito/CK2dll/issues/38

**Comment by matanki-saito** [comment]
月を生成していると思われる箇所
![image](https://user-images.githubusercontent.com/35730970/48304020-cda62a00-e555-11e8-8f31-3efd3548f614.png)

**Comment by matanki-saito** [comment]
リファレンスリスト
![image](https://user-images.githubusercontent.com/35730970/48304050-38effc00-e556-11e8-937d-eab9aa3d985a.png)
これらをすべてやるとしんどいので、CK2と同じように一番上のものだけを調整する。
![image](https://user-images.githubusercontent.com/35730970/48304069-5e7d0580-e556-11e8-8b69-d33ccdf27ebf.png)

**Comment by matanki-saito** [comment]
上の処理には「,」がない気がする。
![image](https://user-images.githubusercontent.com/35730970/48304304-f7158480-e55a-11e8-8ce6-c3d8fb89194c.png)
![image](https://user-images.githubusercontent.com/35730970/48304306-01378300-e55b-11e8-9447-643d97dbaf13.png)

**Comment by matanki-saito** [comment]
" ,"が表示されていないだけっぽかった
![image](https://user-images.githubusercontent.com/35730970/48305752-ab230980-e573-11e8-930e-928bbcbc0ff1.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/48305954-d9561880-e576-11e8-900f-4c964b19c681.png)

1.  スペースをテキストバッファ構造体に格納する
2.  日をバッファに入れる
3.  バッファに1で作ったバッファを結合する
4.  バッファに月を結合する
5. バッファにスペース,を結合する
6. バッファに年を結合する

**Comment by matanki-saito** [comment]
強引に変更。ただし変更されるのはほとんどなく、下記の二箇所ぐらいの模様
![image](https://user-images.githubusercontent.com/35730970/48309561-90c34d00-e5c0-11e8-955d-3d6de6bd9352.png)

![image](https://user-images.githubusercontent.com/35730970/48309566-a8023a80-e5c0-11e8-858b-153d868bb01f.png)

**Comment by matanki-saito** [comment]
リストの２番めにある下記は大変に怪しいということが言えます
![image](https://user-images.githubusercontent.com/35730970/48309663-5e1a5400-e5c2-11e8-87c8-9812e2641ee1.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/48309783-447a0c00-e5c4-11e8-817e-fa4dcc4162e5.png)

1. 月をバッファに入れている
2. それとスペース,を結合
3. それと年を結合

関数は年月日と同じものを使っているので流用する

**Comment by matanki-saito** [comment]
done
![image](https://user-images.githubusercontent.com/35730970/48310366-8e1d2380-e5d1-11e8-927c-cd41a148ad69.png)

**Comment by matanki-saito** [comment]
とりあえずここまでとする
