### ISSUE TITLE
Truncated long province name

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#68]
問題：
州の名前が長いと、末尾の文字が消滅する場合がある。
これは単なる表示上の問題ではなく、州の名前そのものが変更される。

再現性：
常に

再現手順：
1. 1444年のビザンツで開始する。
2. コンスタンティノープルを左クリックする。
3. この時、左下のウインドウには「コンスタンティノープ」と表示され、その左側にキャレットが見える。
4. ESCキーを押す、または×ボタンをクリックして、ウインドウを閉じる。
5. マップ上の州の名前が「コンスタンティノープ」に変更される。

原因：
州の名前が自動的に編集状態になり、なおかつ桁あふれした状態で確定されることが原因だと推測される。

解決策：
暫定的な解決策としては、桁あふれを回避する方法が考えられる。
州ウインドウは interface/provinceview.gui の277行〜286行で定義されている。
1. 281行目を font = "vic_18" などに書き換える（フォントサイズの変更）
2. 283行目を size = { x=200 y=32 } などに書き換える（表示幅の変更）

根本的な解決策としては、州ウインドウを開いた時点で自動的に編集状態にならないようにするのが望ましい。
なお、上の解決策1または2を実施した場合、キャレットは表示されないことが確認できた。

参考画像：
わかりやすくするため、マップフォントのみ変更しています。

再現手順3の状態
![ss1](https://user-images.githubusercontent.com/42687608/47831177-c8691280-ddd2-11e8-9c73-613af19772b1.png)

再現手順5の状態
![ss2](https://user-images.githubusercontent.com/42687608/47831215-f2bad000-ddd2-11e8-86a4-d4b6f3bc7614.png)

**Comment by matanki-saito** [comment]
カスティーリャのやたら長いプロビ名でも起こる問題ですね。

**Comment by matanki-saito** [comment]
とりあえず、その方法で解決してもらえると助かります。。。
