### ISSUE TITLE
Date Format (remained)

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#73]
問題：
日付が日本風の表記になっていない箇所が残っている。

再現性：
常に

再現手順：
1. 適当な国でプレイを開始する（参考画像は1444年のポルトガル）
2. 技術タブで、レベル4の技術の上にカーソルを置く（パターンA）
3. 交易タブで、適当なノードに商人を送り、概要の商人の上にカーソルを置く（パターンB）
4. 外交タブで、適当な国と「関係の改善」を行ない、概要の外交官の上にカーソルを置く（パターンC）

参考画像：

パターンA（yyyy.mm.dd）
![format1](https://user-images.githubusercontent.com/42687608/48312247-4d340780-e5ef-11e8-8796-5b8f97d817e3.png)

パターンB（yyyy.mm.dd）
![format2](https://user-images.githubusercontent.com/42687608/48312250-51f8bb80-e5ef-11e8-947d-451ff4fed314.png)

パターンC（mm月 yyyy）
![format3](https://user-images.githubusercontent.com/42687608/48312252-56bd6f80-e5ef-11e8-83cf-009cee9cd36b.png)

**Comment by matanki-saito** [comment]
最後のものはリストの４つ目かな
![image](https://user-images.githubusercontent.com/35730970/48312539-7a82b480-e5f3-11e8-88ab-d9df55404f2f.png)

**Comment by matanki-saito** [comment]
done
![image](https://user-images.githubusercontent.com/35730970/48313436-d05d5980-e5ff-11e8-9ad8-968b45521dce.png)

**Comment by matanki-saito** [comment]
dot and year
![image](https://user-images.githubusercontent.com/35730970/48313743-f553cb80-e603-11e8-9b1f-44f7e6d97f81.png)
![image](https://user-images.githubusercontent.com/35730970/48313746-00a6f700-e604-11e8-92af-f76c04f38b16.png)

**Comment by matanki-saito** [comment]
したがって単純に考えれば、上と下のdotを0xEと0xFに変えてやればいい
![image](https://user-images.githubusercontent.com/35730970/48313956-4bc20980-e606-11e8-826a-4487dd8761fb.png)

**Comment by matanki-saito** [comment]
と思ったが、「日」をつけられないことに気がついた

**Comment by matanki-saito** [comment]
とりあえず修正可能。「月」のフォントが定義していないので「年」で代用している
![image](https://user-images.githubusercontent.com/35730970/48314462-356b7c00-e60d-11e8-85f0-bd18e0d5e9db.png)

「日」だが、解決策は３つ。
 - 「日」をつけられるか検討する
 - 諦めて /にする。YYYY/MM/DD
 - 元の文章に「日」をつける。 ～～～ YYYY年MM月DD 日～～

**Comment by matanki-saito** [comment]
done
![image](https://user-images.githubusercontent.com/35730970/48369465-f5ce8e00-e6f9-11e8-9e55-b4f629f5c740.png)

**Comment by matanki-saito** [comment]
BEL(0x7)を「月」に割り当てる予定
