### ISSUE TITLE
Text garbling on custom nations

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#75]
問題：
カスタム国家を作成する際に特定の条件で文字化けが発生する。

再現性：
常に

再現手順：
1. 国家選択画面で「カスタム国家」ボタンを押す（DLC「El Dorado」が必要）
2. 日本の「阿波」（現在の徳島県）を選択する。
3. 左上のウインドウの国名が文字化けしている。
4. 国名を削除して修正しようとすると高確率で文字化けする。

原因：
不明

解決策：
不明

参考画像：
![custom_nation](https://user-images.githubusercontent.com/42687608/48459762-f3aa2380-e80e-11e8-9d17-17d853f36f83.png)

**Comment by matanki-saito** [comment]
これは中国チームから指摘されてバグと同じですね。確認してみます

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
この問題は00_cultures.txtの時にも起きました。カスタム国家に特有の問題です。問題は"阿"の文字にあります。これをエスケープすると下記のようになります。
![image](https://user-images.githubusercontent.com/35730970/49969235-6e2fa580-ff6b-11e8-8a70-78581dd320fb.png)
文字シーケンス中に「？」が現れているのが原因です。カスタム国家の名前に？が使えないために問題が置きます。00_cultures.txtのときの修正は「？」をエスケープ対象に加えてもらいました。今回も同じ方法を取れるか相談してみます。
