### ISSUE TITLE
Illegal save date

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#76]
重要：
[開発版](https://cdn.discordapp.com/attachments/439712817377968138/518078767533522984/dev_steam_EU4_1.25-1.27_mbdll_build_20181130.1.zip)に固有の問題です。[配布版](https://github.com/matanki-saito/EU4dll/releases/download/Build-20181111.1/steam_EU4_1.25-1.27_mbdll_build_20181111.1.zip)では発生しません。

問題：
セーブデータの日付が不正な値になる。

再現性：
常に

再現手順：
1. 任意の国でプレイを開始する。
2. 開始直後にセーブする。
3. ロード画面を確認すると日付が「-5000年3月2日」になっている。

補足：
1. 手動セーブではなくオートセーブでも同じ現象が発生します。
2. セーブした時の日付によらず、セーブデータの日付は常に「-5000年3月2日」となります。
3. 異常な日付のセーブデータをロードすると「5000年3月2日」になります（マイナスが消えます）

原因：
日付を日本風の表記に変える修正の副作用だと推測されます。

解決策：
不明

参考画像：
![ss2](https://user-images.githubusercontent.com/42687608/49324178-2cb2f980-f56c-11e8-8479-349ac198810f.png)

**Comment by matanki-saito** [comment]
セーブデータがdot formatではなくなっている。
![image](https://user-images.githubusercontent.com/35730970/49324344-093d7e00-f56f-11e8-9240-fadca4082b53.png)

表示処理だけに限定されていない

**Comment by matanki-saito** [comment]
不自然にyyyy.mm.ddで表示されていたのはmodelをそのままviewに渡していたからなのか...

**Comment by matanki-saito** [comment]
おそらく下記全て個別に対応しないと駄目な感じですね…
https://paratranz.com/projects/76/strings?text=%24DATE%24
yyyy.mm.ddの部分はこのまま表示する仕様とします。

**Comment by matanki-saito** [comment]
PRにしたのでクローズ
