### ISSUE TITLE
Regiment Name

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/EU4dll#81]
連隊名が日本語的表記ではない。
（例：越後の1st連隊）

**Comment by matanki-saito** [comment]
第一のような形が自然でしょうか

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/49970169-d2ebff80-ff6d-11e8-8fcb-d4d3189ac1ee.png)

**Comment by matanki-saito** [comment]
テキストはこれかな
![image](https://user-images.githubusercontent.com/35730970/49970332-468e0c80-ff6e-11e8-8085-5b4539b02a84.png)

**Comment by matanki-saito** [comment]
ORDERはtext_l_englishの下記の部分あたりで動的に変えられそうです。
![image](https://user-images.githubusercontent.com/35730970/49970768-bf419880-ff6f-11e8-995f-98015c7e42df.png)

paratranzだと下記がSTです。
https://paratranz.cn/projects/76/strings?id=4161990

**Comment by matanki-saito** [comment]
合わせて修正したほうが良さそうです
![image](https://user-images.githubusercontent.com/35730970/49971061-89e97a80-ff70-11e8-88f9-e3c0402ece23.png)

https://paratranz.cn/projects/76/strings?text=%24HOME%24%E3%81%AE

**Comment by matanki-saito** [comment]
ちなみにST:0 "st"をST:0 "テスト"などにすると下記のようになります。
![image](https://user-images.githubusercontent.com/35730970/49971117-b1404780-ff70-11e8-8a41-a3f12b3420c8.png)
