### ISSUE TITLE
File name garbling in text box

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#89]
問題：
ファイル名に日本語が含まれるセーブデータを選択すると文字化けする。

再現性：
常に

再現手順：
1. ファイル名に日本語が含まれるセーブデータを作成する。
2. ゲーム内でセーブダイアログを開き、先ほど作成したセーブデータを選択する。
3. ダイアログ下部の入力エリアを見るとファイル名が文字化けしている。

原因：
不明

解決策：
不明

参考画像：
![ss](https://user-images.githubusercontent.com/42687608/50040380-99a6b300-0085-11e9-8dca-dcb064b265fe.png)

**Comment by matanki-saito** [comment]
これはCK2と同じ方法で解決可能に見える。すなわちUTF-8を取得後、escapedCharacterSequenceに変換する。

**Comment by matanki-saito** [comment]
英語
![image](https://user-images.githubusercontent.com/35730970/56287213-b7c91080-6156-11e9-822b-3d9c9cedde25.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/56292708-9ec65c80-6162-11e9-8362-ef03e0da73d9.png)

![image](https://user-images.githubusercontent.com/35730970/56292734-a980f180-6162-11e9-8b6f-9ed0c603d9cf.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/56304058-397d6600-6178-11e9-8dfe-eff4c238bc0a.png)

**Comment by matanki-saito** [comment]
クリックして、インプットエリアに挿入されるときには別の関数が呼ばれる。
![image](https://user-images.githubusercontent.com/35730970/56524531-8308ef00-6584-11e9-9681-9c6f671c8284.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/56524713-e135d200-6584-11e9-8bbd-1567bd80f337.png)

**Comment by matanki-saito** [comment]
done
![image](https://user-images.githubusercontent.com/35730970/56529224-61f7cc80-658b-11e9-8af4-0f83b97da493.png)

**Comment by matanki-saito** [comment]
確認してもらったのでClose
