### ISSUE TITLE
Order of Japanese name

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#98]
問題：
日本人の姓と名の順序が逆になっている。

再現性：
常に

再現手順：
省略

原因：
EU4の仕様上、王朝名（ファミリーネーム）が必ず後ろに来るため。

解決策：
特定の国、あるいは文化の時だけ、姓と名の順序を逆転するパッチを作成できれば解決できる・・・かも？

**Comment by matanki-saito** [comment]
このあたり
![image](https://user-images.githubusercontent.com/35730970/50236393-a0bf1f80-03fd-11e9-9d3e-e0ce543aa0fa.png)

**Comment by matanki-saito** [comment]
NAMEとHEIR_NAMEあたり
https://paratranz.com/projects/76/strings?id=4167501

**Comment by matanki-saito** [comment]
(,,ﾟДﾟ)ｱﾔｼｨ
![image](https://user-images.githubusercontent.com/35730970/50238317-6efc8780-0402-11e9-9899-48dfb3ec6e36.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/50238933-03b3b500-0404-11e9-8865-372719719699.png)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
ん、もしかして可変長の引数なのか？

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/52658987-ba816c80-2f3f-11e9-9015-7be6fa88ed12.png)

**Comment by matanki-saito** [comment]
黄色い関数はたくさん使われていて、おそらくテキストを合成する？もの。
 - ecx：バッファ
 - edx：元の？テキストのキー
 - push1：埋め込む？テキストのキー
 - push2：埋め込むテキストのオブジェクト

**Comment by matanki-saito** [comment]
したがって名前のテキストの構築は黄色い関数の中ではなく、その上の方で、用意されていた。具体的には「de valois」が用意されて、
![image](https://user-images.githubusercontent.com/35730970/52659605-0385f080-2f41-11e9-8039-7e711ea437d6.png)
次に「Louis」が用意されて、
![image](https://user-images.githubusercontent.com/35730970/52659623-113b7600-2f41-11e9-94d6-cfa0320711e5.png)
くっついて「Louse de valois」になる。
![image](https://user-images.githubusercontent.com/35730970/52659704-4b0c7c80-2f41-11e9-93b3-53bb4c943bfd.png)

**Comment by matanki-saito** [comment]
１つ目の関数（sub_853280）は、すぐ上にpush eaxがあって引数をもらってそうに見えるが、それは違くて、ただスタックに積まれているだけ。

**Comment by matanki-saito** [comment]
順番を変えるのは２つ目の引数の位置変えれば良いのか？
 - edx: 前にくっつくテキスト
 - ecx: バッファ？
 - push: 後ろにくっつくテキスト
っぽいのでedxとpushを入れ替える

**Comment by matanki-saito** [comment]
ひっくり返す処理をすることで、下記のようにLouis de valoisは de valoisLouisになる。
![image](https://user-images.githubusercontent.com/35730970/52688937-cbf86200-2f9b-11e9-9dd3-52fc8444875b.png)

**Comment by matanki-saito** [comment]
一方、NAMEはものすごくたくさんあり、不可能なのではないか
![image](https://user-images.githubusercontent.com/35730970/52689421-6c9b5180-2f9d-11e9-96d1-e2616daef987.png)

**Comment by matanki-saito** [comment]
王様の名前はMONARCH_TITLEっぽい。
![image](https://user-images.githubusercontent.com/35730970/52690510-4677b080-2fa1-11e9-85ff-30bdfb2d7ef4.png)

**Comment by matanki-saito** [comment]
ふむ... (,,ﾟДﾟ)
![image](https://user-images.githubusercontent.com/35730970/52690956-ae7ac680-2fa2-11e9-8340-4ef4feb4f53c.png)

**Comment by matanki-saito** [comment]
どうもここではKingとCharles VII de valoisをくっつけているらしい

**Comment by matanki-saito** [comment]
ちょっと上の方では、Carles VII de Valoisができている。
![image](https://user-images.githubusercontent.com/35730970/52691391-0ebe3800-2fa4-11e9-95c6-11d0dbf582be.png)

**Comment by matanki-saito** [comment]
そしてこの関数の中では、Chares VIIとde Valoisがくっついているらしいことがわかった。

**Comment by matanki-saito** [comment]
なるほど、この関数はecx渡しされたオブジェクトから合成している。渡されたオブジェクトの先頭からoffset+14hに最初のテキスト（Charles VII）が入っていて、offset+6Chの先の+4されたところに後のテキスト（de valois）がある。

**Comment by matanki-saito** [comment]
まず最初にde valoisとスペースをくっつけて、その次に、「 de valois」と「Charles VII」をsub_33A0D0でくっつけている。

![image](https://user-images.githubusercontent.com/35730970/52697435-ceb38100-2fb4-11e9-84da-2d3e1f10ec28.png)

つまり引数をひっくり返せば、ひっくり返って結合される気がする

**Comment by matanki-saito** [comment]
(´ﾍ｀；)ｳｰﾑ…消えてしまった。
![image](https://user-images.githubusercontent.com/35730970/52701547-cdd31d00-2fbd-11e9-9c23-3a86bca5cb2b.png)

**Comment by matanki-saito** [comment]
文字列を後ろに「付け足す」関数だからか。

**Comment by matanki-saito** [comment]
(´ﾍ｀；)ｳｰﾑ…、一度空にして、くっつけるか？

**Comment by matanki-saito** [comment]
とりあえず、見通しを立てた

**Comment by oooFUNooo** [comment]
姓名の順序を逆転させた場合に、一部の漢字が文字化けすることを確認しました。

確認できている組み合わせは次の通りで、すべてエスケープ文字 0x11 の後に来る文字が化けています。
- 伊達→達
- 伊東→東
- 上杉→下杉
- 一色→丁色
- 山名→山后

![bug](https://user-images.githubusercontent.com/42687608/52901312-71822e80-3245-11e9-872a-f7bc6321cbbb.jpg)

**Comment by matanki-saito** [comment]
4E0A：上
4E0B：下
なので、人つづれているのだと思います。理由は不明です...

**Comment by matanki-saito** [comment]
↑はエンコードの問題のため、このissueはCloseします。
