### ISSUE TITLE
Shorter truncated width

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4dll#99]
問題：
日本語が桁あふれする時の表示幅が、英語が桁あふれする時の表示幅よりも短い。

再現性：
常に

再現手順：
1. 1718年「四国同盟戦争」をオーストリアで開始する。
2. 画面右下の国旗アイコンをクリックし、戦況ウインドウを表示する。
3. 国名リストを比較する。

原因：
桁あふれを判定する際にフォントの横幅が正しく計算されていない可能性がある。

解決策：
上の原因を特定して修正する。

参考画像：

英語環境
![ss2](https://user-images.githubusercontent.com/42687608/50092713-2c944880-0252-11e9-8fcc-f80f3c0cfcd7.jpg)

日本語環境
![ss1](https://user-images.githubusercontent.com/42687608/50092723-3322c000-0252-11e9-8b8b-2ebff4882f51.jpg)

**Comment by oooFUNooo** [comment]
原因の推測：
日本語データに含まれるエスケープ文字が
桁あふれを計算するときの文字数に含まれている可能性がある。

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/50986742-fb562200-154a-11e9-9ef1-4859c2f082bc.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/50986762-0ad56b00-154b-11e9-8a5b-10c3ef2d39a0.png)

**Comment by matanki-saito** [comment]
(´ﾍ｀；)ｳｰﾑ…しんどそう

**Comment by matanki-saito** [comment]
むしろ悪化してしまった　謎い
![image](https://user-images.githubusercontent.com/35730970/51037486-b33f0a00-15f3-11e9-90cc-daadaddb5d50.png)

**Comment by matanki-saito** [comment]
わからんゲソね
![image](https://user-images.githubusercontent.com/35730970/51040999-3e240280-15fc-11e9-963c-866d0bce4bed.png)

**Comment by matanki-saito** [comment]
ムズムズのムズ

**Comment by matanki-saito** [comment]
１つ目の関数は多分KERNINGっぽい

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/51072053-fce42f00-169d-11e9-89fb-07332bb8d8e8.png)

**Comment by matanki-saito** [comment]
ポルトガル領ブラジルだと、ediが0x16なので、_ポルトガル領ブ（行頭にスペースが自動的に入る）までは入ると判定されるが、push dword ptr[eax]が0xAでそれより短くされて_ポルトになってしまう。

**Comment by matanki-saito** [comment]
eaxはsub_E78CD0で決定されるが、この中の処理がいまいちわからんな
![image](https://user-images.githubusercontent.com/35730970/51072481-ceb61d80-16a4-11e9-8199-928ca287ca06.png)

**Comment by matanki-saito** [comment]
¿¿¿ ?؟؟؟  (,,ﾟДﾟ) ⁇؟⁇⁇ 
わからん
